### ISSUE TITLE
 Cannot find icon: C:\......\FreeCAD\Mod\FEM_FrontISTR\.\Resources/FrotISTR.svg

### ISSUE THREAD

**Issue by johnnygeling** [FrontISTR/FEM_FrontISTR#10]
Hello,

I got this message in the report view. 
 Cannot find icon: C:\......\FreeCAD\Mod\FEM_FrontISTR\.\Resources/FrotISTR.svg

![afbeelding](https://user-images.githubusercontent.com/20334327/171667231-df0754b2-65a3-42b3-b6cd-e9be0e0d0c42.png)

The file is not in the resource folder after installation with the addon manager in freecad:

[code]
OS: Windows 10 (10.0)
Word size of FreeCAD: 64-bit
Version: 0.20.28936 (Git)
Build type: Release
Branch: master
Hash: b02705d79f
Python 3.8.13, Qt 5.12.9, Coin 4.0.0, OCC 7.5.3
Locale: Dutch/Belgium (nl_BE)
Installed mods: 
  * 3DfindIT 1.2.0
  * A2plus 0.4.55a
  * ArchTextures
  * Assembly3 0.11.3
  * Assembly4 0.11.12
  * BIM 2021.12.0
  * cadquery_module
  * CommandPanel
  * CurvedShapes 1.0.3
  * Curves 0.3.0
  * Defeaturing
  * dodo
  * dxf-library
  * dxf_library
  * ExplodedAssembly
  * exploded_animation
  * FEM_FrontISTR 0.1.0
  * Glass
  * IconThemes
  * ImportNURBS
  * Manipulator 1.4.3
  * MeshRemodel 1.8919.0
  * nurbs
  * parts_library
  * PieMenu
  * Plot 2022.4.17
  * reconstruction
  * Reinforcement
  * Render 2022.1.0
  * Reporting
  * SearchBar 1.0.1
  * SelectorToolbar
  * sheetmetal 0.2.49
  * Silk -228708064.0.0
  * SlopedPlanesMacro
  * symbols_library
  * timber
  * WebTools
  * workfeature
  * workfeature-macro
  * yaml-workspace
[/code]

**Comment by kinagaki** [comment]
@johnnygeling Thanks for reporting!
