### ISSUE TITLE
ETA on Linux support?

### ISSUE THREAD

**Issue by luzpaz** [FrontISTR/FEM_FrontISTR#2]
Any ideas ? What are the roadblocks ?

**Comment by scottmudge** [comment]
I compiled FrontISTR on linux and installed the workbench.

The workbench launches and writes the input file, but the `front1` binary just crashes and says "Error()", without much additional information.

**Comment by luzpaz** [comment]
bump

**Comment by luzpaz** [comment]
Any progress ?

**Comment by kinagaki** [comment]
@luzpaz 
Linux support has been added, with compatibility limited to Ubuntu 20.04.
